// Hiérarchie administrative du Portugal : District → Concelho → Freguesias
// Structure: PORTUGAL[district][concelho] = string[]
export const PORTUGAL: Record<string, Record<string, string[]>> = {
  'Aveiro': {
    'Águeda': ['Águeda e Borralha','Barrô e Aguada de Cima','Fermentelos','Macinhata do Vouga','Mourisca do Vouga','Óis da Ribeira e Sérem','Recardães e Espinhel','Travassô e Óis do Bairro','Trofa','Valongo do Vouga'],
    'Albergaria-a-Velha': ['Albergaria-a-Velha e Valmaior','Branca','Ribeira de Fráguas','São João de Loure e Frossos'],
    'Anadia': ['Avelãs de Cima','Moita','Paredes do Bairro','Sangalhos','São Lourenço do Bairro','Tamengos e Vila Nova de Monsarros','Vilarinho do Bairro'],
    'Arouca': ['Arouca','Burgo','Cabreiros e Albergaria da Serra','Canelas','Chave','Covelo de Paivó','Escariz','Fermedo','Janarde','Mansores','Moldes','Piedade','Rossas','Santa Eulália','São Miguel do Mato','Tropeço','Urrô','Várzea'],
    'Aveiro': ['Aradas','Cacia','Eixo e Eirol','Esgueira','Glória e Vera Cruz','Nariz','Oliveirinha','Requeixo, Nossa Senhora de Fátima e Nariz','Santa Joana'],
    'Castelo de Paiva': ['Bairros','Castelo de Paiva','Fornos','Lebução','Raiva, Pedorido e Paraíso','Santa Maria de Sardoura'],
    'Espinho': ['Espinho','Guetim'],
    'Estarreja': ['Avanca','Beduído e Veiros','Canelas e Fermelã','Pardilhó','Salreu'],
    'Ílhavo': ['Gafanha da Encarnação','Gafanha da Nazaré','Gafanha do Carmo','Ílhavo (São Salvador)'],
    'Mealhada': ['Antes e Doze','Barcouço','Casal Comba','Luso','Mealhada','Pampilhosa','Vacariça','Ventosa do Bairro'],
    'Murtosa': ['Bunheiro','Monte','Murtosa','Torreira'],
    'Oliveira de Azeméis': ['Carregosa','Cesar','Fajões','Loureiro','Macinhata da Seixa','Madail','Nogueira do Cravo','Oliveira de Azeméis, Santiago de Riba-Ul, Ul, Macinhata da Seixa e Madail','Palmaz','Pinheiro da Bemposta, Travanca e Palmaz','São Roque','Vila de Cucujães'],
    'Oliveira do Bairro': ['Amoreira do Vouga','Bustos, Troviscal e Mamarrosa','Oiã','Oliveira do Bairro','Palhaça'],
    'Ovar': ['Cortegaça','Esmoriz','Maceda','Ovar','São João de Ovar','São Vicente de Pereira Jusã','Válega'],
    'Santa Maria da Feira': ['Argoncilhe','Arrifana','Caldas de São Jorge e Pigeiros','Canedo, Vale e Vila Maior','Escapães','Espargo','Fiães','Fornos','Girabolhos','Lobão, Gião, Louredo e Guisande','Lourosa','Milheirós de Poiares','Mosteirô','Nogueira da Regedoura','Paços de Brandão','Romariz','Sanfins, Espargo e Seirós','Santa Maria de Lamas','São João de Ver','São Paio de Oleiros','Souto'],
    'São João da Madeira': ['São João da Madeira'],
    'Sever do Vouga': ['Cedrim e Paradela','Dornelas','Rocas do Vouga','Sever do Vouga'],
    'Vagos': ['Calvão','Covão do Lobo e Mamodeiro','Fonte de Angeão','Gafanha da Boa Hora','Ouca','Vagos','Vilanova'],
    'Vale de Cambra': ['Arões','Cepelos','Codal','Junqueira','Macieira de Cambra','Roge','São Pedro de Castelões','Vale de Cambra'],
  },
  'Beja': {
    'Aljustrel': ['Aljustrel','Ervidel','Rio de Moinhos','São João de Negrilhos','Torrão'],
    'Almodôvar': ['Aldeia dos Fernandes','Almodôvar e Graça dos Padrões','Ameixial','Rosário','Santa Clara-a-Nova e Gomes Aires','São Barnabé','Vale de Palheiros'],
    'Alvito': ['Alvito','Vila Nova da Baronia'],
    'Barrancos': ['Barrancos'],
    'Beja': ['Albernoa e Trindade','Alfundão e Peroguarda','Aljustrel... (ver Aljustrel)','Beja (Salvador e Santa Maria da Feira)','Beja (Santiago Maior e São João Baptista)','Cabeça Gorda','Mombeja','Santa Vitória e Missa','Trigaches e São Brissos'],
    'Castro Verde': ['Casével e Entradas','Castro Verde e Casével','Santa Bárbara de Padrões'],
    'Cuba': ['Albernoa','Cuba','Faro do Alentejo','Vila Alva','Vila Ruiva'],
    'Ferreira do Alentejo': ['Alfundão','Canhestros','Ferreira do Alentejo e Canhestros','Odivelas','Peroguarda'],
    'Mértola': ['Alcaria Ruiva','Corte do Pinto','Espírito Santo','Mértola','Santana de Cambas','São João dos Caldeireiros','São Miguel do Pinheiro, São Pedro de Solis e São Sebastião dos Carros'],
    'Moura': ['Amareleja','Moura (Castelo e Santo Agostinho)','Póvoa de São Miguel','Safara e Santo Aleixo da Restauração','Santo Amador','Sobral da Adiça'],
    'Odemira': ['Almograve','Boavista dos Pinheiros','Longueira-Almograve','Luzianes-Gare','Odemira','Relíquias','Sabóia','Santa Clara-a-Velha','São Luís','São Martinho das Amoreiras','São Teotónio','Vale de Santiago','Vila Nova de Milfontes','Zambujeira do Mar'],
    'Ourique': ['Garvão e Santa Luzia','Ourique','Panoias e Conceição','Santana da Serra'],
    'Serpa': ['Brinches e Enxoé','Pias','Serpa (Salvador e Santa Maria)','Vale de Vargo','Vila Nova de São Bento'],
    'Vidigueira': ['Pedrógão','Selmes','Vidigueira e Vila de Frades'],
  },
  'Braga': {
    'Amares': ['Amares e Figueiredo','Barreiros e Crespos','Besteiros','Bouro (Santa Maria) e Bouro (Santa Marta)','Caldelas','Carrazedo e Vila Cova','Dornelas','Goães','Lago','Paranhos','Sequeiros e Caldelas'],
    'Barcelos': ['Abade de Neiva','Adães','Aguiar','Airão Santa Maria, Airão São João e Vermil','Aldreu','Alheira','Alvelos','Arcozelo','Areias','Arões','Balugães','Barcelinhos','Barcelos, Vila Boa e Vila Frescainha (São Martinho e São Pedro)','Carapeços','Carreira e Besteiros','Carvalhal','Chavão','Chorente, Góios, Courel, Pedra Furada e Gueral','Cossourado','Couto','Creixomil','Durrães','Encourados','Faria','Feitos','Fonte Coberta','Fornelos e Queimadela','Fragosela','Galegos (Santa Maria) e Galegos (São Martinho)','Gilmonde','Góios','Grimancelos','Labruja','Lama','Lijó','Macieira de Rates','Mariz','Martim','Milhazes','Minhotães','Monte de Fralães','Moure','Negreiros e Chavão','Oliveira','Panque','Paradela','Pereira','Perelhal','Pousa','Remelhe','Rio Covo (Santa Eulália)','Roriz','Silva','Silveiros','Tamel (Santa Leocádia) e Vilar do Monte','Ucha','Várzea','Vila Cova','Vila Frescainha (São Pedro)','Vila Seca'],
    'Braga': ['Aveleda','Braga (Maximinos, Sé e Cividade)','Braga (São José de São Lázaro e São João do Souto)','Braga (São Vítor)','Caldelas','Cabreiros e Passos (São Julião)','Crespos e Panoias','Dume e Semelhe','Esporões','Figueiredo, Oliveira (São Pedro) e Barbudo','Lomar e Arcos','Merelim (São Paio), Panque e Aborim','Merelim (São Pedro) e Frossos','Mire de Tibães','Morreira e Trandeiras','Nogueira, Fraião e Lamaçães','Palmeira','Panoias e Parada de Tibães','Pedralva e Mire de Tibães','Priscos','Real, Dume e Semelhe','Ruilhe','São Jerónimo Real','São José de São Lázaro','São Pedro de Merelim','Tadim','Tebosa'],
    'Cabeceiras de Basto': ['Alvite e Moure','Basto','Bueiros','Cabeceiras de Basto','Cavez','Faia','Gondiães','Outeiro','Painzela e Útimo','Refojos de Basto, Outeiro e Painzela','Riodouro','Vilar de Cunhas'],
    'Celorico de Basto': ['Arnóia','Borba de Montanha','Bragade','Caçarilhe e Infesta','Canedo de Basto','Carvalho','Corgo','Fervença','Molares','Moure e Memorigo','Pedraído','Ribas','Riodouro','Segude e Gundar','Veade, Gagos e Molares'],
    'Esposende': ['Antas e Mujães','Apúlia e Fão','Barcelos (ver)','Belinho e Mar','Curvos e Gemunde','Esposende, Marinhas e Gandra','Forjães','Gemunde','Marinhas'],
    'Fafe': ['Arões (Santa Cristina) e Arões (São Romão)','Aveleda e Freixo','Cepães e Fareja','Estorãos','Fafe','Fornelos e Lagares','Freitas','Golães','Medelo','Monte, Agrela e Fontainhas','Moreira do Rei e Antime','Passos','Regadas','Revelhe','Ribeiros','São Gens','Serafão','Silvares (São Clemente) e Silvares (São Martinho)','Torres','Várzea Cova'],
    'Guimarães': ['Abação e Gémeos','Airão São João','Aldão','Arosa e Castelões','Azurém','Brito','Caldas das Taipas e Nespereira','Candoso (São Martinho) e Candoso (São Tiago)','Conde','Costa','Creixomil e Maceira','Fermentões','Figueiredo','Gondar','Guardizela','Infantas e Lordelo','Irivo','Leitões, Oleiros e Figueiredo','Longos','Lordelo','Mesão Frio e Oliveira (São Pedro)','Moreira de Cónegos','Morreira','Nespereira','Pencelo e Gandarela','Pinheiro','Polvoreira','Ponte','Poças','Ronfe','Sande (São Lourenço) e Balazar','Sande (São Martinho) e Penha','Sande (Vila Nova) e Sande (São Clemente)','Selho (São Jorge) e Selho (São Cristóvão)','Selho (São Lourenço)','Silvares','Souto (Santa Maria), Souto (São Miguel) e Gondomar','Urgezes','Vila Nova de Sande e São Salvador de Briteiros'],
    'Póvoa de Lanhoso': ['Águas Santas e Moure','Brunhais','Calvos e Mós','Covide e Midões','Esperança','Frades','Garfe e Geraz do Minho','Geraz do Minho','Lanhoso','Louredo','Moure','Póvoa de Lanhoso','Rendufas','Serzedelo','Sobradelo da Goma','Verim e Serafão'],
    'Terras de Bouro': ['Balança','Brufe','Campo do Gerês','Chamoim e Vilar','Chorense e Monte','Cibões','Covide','Gondoriz','Moimenta','Monte','Rio Caldo','Souto','Valdosende','Vieira do Minho'],
    'Vieira do Minho': ['Campos e Louredo','Cantelães','Caniçada','Cerdeirinhas e Agra','Eira Vedra','Guilhofrei','Mosteiro, Ruivães e Novais','Parada do Bouro','Rossas','Salamonde','Soengas','Ventosa','Vieira do Minho'],
    'Vila Nova de Famalicão': ['Antas','Avidos e Lagoa','Bairros','Brufe','Calendário','Carreira e Bente','Castelões','Cruz','Delães','Esmeriz e Cabeçudos','Fradelos','Gavião','Gondifelos, Cavalões e Outiz','Joane','Lousado','Mouquim','Nine','Novais','Oliveira (Santa Maria)','Pedome','Portela','Ribeirão','Ruivães e Novais','Ruilhe','São Cosme e São Damião','São Martinho do Vale','Seide','Telhado','Vale (São Cosme), Telhado e Portela','Vermoim','Vilarinho das Cambas'],
    'Vila Verde': ['Aboim da Nóbrega','Atiães','Barbudo','Cabanelas','Cervães','Duas Igrejas','Escariz (São Mamede) e Escariz (São Tiago)','Esqueiros, Nevogilde e Travassós','Freiriz','Goães e Ponte','Gómide e Gual','Lanhas','Lage','Loureira','Marrancos','Morgade','Moure e Cornes','Oriz (Santa Marinha) e Oriz (São Miguel)','Passô','Pera e Caçarelhes','Prado','Roriz','Sande','São João Batista','Soutelo','Turiz','Valdreu','Valbom e Atiães','Vila Chã','Vila de Prado','Vila Verde'],
    'Vizela': ['Caldas de Vizela (São Miguel) e Caldas de Vizela (São João)','Infias','Nespereira (São Tomé)','Novais','Selho (São Jorge)','Tagilde e Vizela (São Paio)'],
  },
  'Bragança': {
    'Alfândega da Fé': ['Alfândega da Fé','Eucísia, Gouveia e Valverde','Ferradosa','Gebelim','Saldonha','Sambade','Sendim da Ribeira','Sendim da Serra','Soeima','Vale Pereiro','Vilar Chão','Vilarinho da Castanheira'],
    'Bragança': ['Alfaião','Babe','Baçal','Bragança (Meixedo)','Bragança (Nogueira)','Bragança (Samil)','Bragança (Santa Maria)','Bragança (Sé)','Castrelos e Carragosa','Coelhoso','Deilão','Donai','Espinhosela','Fresulfe e Mofras','Gimonde','Gondesende','Gostei','Grijó de Parada','Izeda','Macedo do Mato','Milhão','Mós','Nozelos','Outeiro','Parada','Parâmio','Pinela','Quintanilha','Quintela de Lampaças','Rabal','Rio de Onor','Salsas','Samil','São Julião de Palácios e Deilão','Sortes','Zoio'],
    'Carrazeda de Ansiães': ['Beira Grande','Belver e Mogo de Malta','Carrazeda de Ansiães','Fontelonga','Lavandeira, Beira Grande e Selores','Linhares','Marzagão','Pereiros','Pinhal do Norte','Pombal','Ribalonga','Selores','Seixo de Ansiães','Vilarinho da Castanheira'],
    'Freixo de Espada à Cinta': ['Freixo de Espada à Cinta','Lagoaça e Fornos','Ligares','Mazouco','Poiares'],
    'Macedo de Cavaleiros': ['Bornes e Burga','Corujas, Morais e Vilar do Monte','Espadanedo, Edrosa e Edral','Ferreira','Foz do Tua','Grandais e Sezulfe','Lagoa e Carvalho','Lamalonga','Lamas e Podence','Macedo de Cavaleiros','Olmos e Pesqueira','Peredo de Bemposta','Sanhoane','Santa Combinha','São Pedro de Vale do Conde','Talhas','Talhinhas','Vale Benfeito','Vilarinho de Agrochão','Vinhas'],
    'Miranda do Douro': ['Constantim e Vale de Mira','Duas Igrejas','Genísio','Ifanes','Miranda do Douro','Malhadas','Palaçoulo','Picote e Bemposta','Póvoa','São Martinho de Angueira','Sendim','Silva','Vilarinho dos Galegos'],
    'Mirandela': ['Abambres','Abreiro','Aguieiras','Alvites','Avantos e Romeu','Barcel','Bouça','Cabanelas','Caravelas','Cedães','Cobro','Fradizela','Frechas','Freixeda','Lamas de Orelhão','Marmelos','Mirandela','Múrias','Navalho','Pereira','São Pedro Velho','São Salvador','Sendim da Serra','Suçães','Torre de Dona Chama','Vale de Salgueiro','Vale de Telhas','Valverde','Vila Verde'],
    'Mogadouro': ['Azinhoso','Brunhoso e Brunhosinho','Castanheira','Castro Vicente','Granja','Meirinhos','Mogadouro, Brunhoso e Brunhosinho','Peredo da Bemposta','Remondes','Sanhoane','São Martinho do Peso','Soutelo','Tó','Travanca','Urrós','Vale da Madre','Ventozelo'],
    'Torre de Moncorvo': ['Açoreira','Adeganha','Cabeça Boa','Cardanha','Carviçais','Castedo','Horta da Vilariça','Larinho','Lousal','Mós','Peredo dos Castelhanos','Torre de Moncorvo','Urros'],
    'Vila Flor': ['Assares','Benlhevai','Candoso','Carvalho','Freixiel','Nabo','Roios','Samões','Santa Comba de Rossas','Trindade','Vilas Boas','Vila Flor'],
    'Vimioso': ['Argela','Caçarelhos','Carção','Matela','Pinelo','Populares','São Martinho de Angueira','Uva','Vilar Seco'],
    'Vinhais': ['Agrochão','Alvaredos','Edral','Edrosa','Ervedosa','Fresulfe','Moimenta','Mofreita e Roças','Montouto','Nunes e Ousilhão','Paçó','Pinheiro Novo','Quelhe','Rebordainhos','Rebordelo','Rio de Fornos','Santa Cruz','Santalha','Santo André','Sobreiro de Baixo','Soeira','Travessos de Baixo','Tuizelo','Vila Verde e Fradizela','Vinhais'],
  },
  'Castelo Branco': {
    'Belmonte': ['Belmonte e Colmeal da Torre','Caria','Inguias','Maçainhas'],
    'Castelo Branco': ['Alcains','Almaceda','Benquerenças','Castelo Branco','Cebolais de Cima e Retaxo','Escalos de Baixo e Lousa','Escalos de Cima','Juncal do Campo','Lardosa','Louriçal do Campo','Malpica do Tejo','Monforte da Beira','Ninho do Açor','Póvoa de Rio de Moinhos e Cafede','Salgueiro do Campo','Santo André das Tojeiras','Sarzedas','Sobral do Campo','Tinalhas'],
    'Covilhã': ['Aldeia do Carvalho','Aldeia de São Francisco de Assis','Barco','Boidobra','Canhoso','Cantar Galo e Vale Formoso','Casegas','Covilhã e Canhoso','Dominguizo','Erada','Ferro','Orjais','Paul','Peraboa','Peso','São Jorge da Beira','São Martinho','Tortosendo','Unhais da Serra','Vale Formoso','Verdelhos','Vila do Carvalho'],
    'Fundão': ['Alcaide','Alcaria','Alcongosta e Almaceda','Alpedrinha','Bogas de Cima e Bogas de Baixo','Castelejo','Donas','Eira Pedrinha','Fatela','Fundão','Pinheiro','Póvoa da Atalaia e Atalaia do Campo','Salgueiro','Silvares','Soalheira','Souto da Casa','Telhado','Vale de Prazeres'],
    'Idanha-a-Nova': ['Idanha-a-Nova e Alcafozes','Ladoeiro','Medelim e Monfortinho','Monsanto e Fatela','Oledo','Penha Garcia','Proença-a-Velha','Rosmaninhal','Segura','Toulões'],
    'Oleiros': ['Abrantes','Álvaro','Cambas e Estreito','Madeirã','Mosteiro','Oleiros','Orvalho','Sarnadas de Rodão','Sobral de São Miguel'],
    'Penamacor': ['Aldeia do Bispo','Benquerença','Escaição','Meimão','Meimoa','Penamacor e Aldeia do Bispo','Pedrogão de São Pedro','Salvador','Serra'],
    'Proença-a-Nova': ['Alvito da Beira e Montes da Senhora','Brunhoso','Cardigos','Mação (ver Mação)','Peral','Proença-a-Nova','São Pedro do Esteval','Sobreira Formosa e Peral'],
    'Sertã': ['Água de Alte','Cernache do Bonjardim, Nesperal e Palhais','Cumeada','Ermida','Figueiredo','Marmeleiro','Pedrógão Pequeno','Sertã','Troviscal','Várzea dos Cavaleiros'],
    'Vila de Rei': ['Fundada','São João do Peso e Fundada','Vila de Rei'],
    'Vila Velha de Ródão': ['Fratel','Orvalho (ver Oleiros)','Perais','Sarnadas de Ródão','Vila Velha de Ródão'],
  },
  'Coimbra': {
    'Arganil': ['Arganil','Benfeita','Celavisa','Côja e Barril de Alva','Folques','Piódão','São Martinho da Cortiça','Secarias','Teixeira e Tecelagem','Vila Cova de Alva'],
    'Cantanhede': ['Ançã','Bolho','Cadima','Cantanhede e Pocariça','Cordinhã e Cabeços','Febres','Murtede','Ourentã','Portunhos','Sepins'],
    'Coimbra': ['Antanhol','Antuzede e Vil de Matos','Assafarge e Antanhol','Botão','Brasfemes','Ceira','Coimbra (Sé Nova)','Coimbra (Santa Clara)','Coimbra (Santo António dos Olivais)','Coimbra (São Martinho do Bispo e Ribeira de Frades)','Eiras e São Paulo de Frades','Lamarosa','Pedrulha','São Silvestre','São João do Campo','Trouxemil e Torre de Vilela','Vila Nova de Poiares (ver)'],
    'Condeixa-a-Nova': ['Anobra','Condeixa-a-Nova','Ega','Furadouro','Sebal e Belide'],
    'Figueira da Foz': ['Bom Sucesso','Brenha','Buarcos e São Julião','Ferreira-a-Nova','Lavos','Maiorca','Marinha das Ondas','Moinhos','Morros e São Simão de Litém','Paião','Quiaios','Santana','Tavarede','Vila Verde'],
    'Góis': ['Cadafaz e Colmeal','Góis','Janarde e São Brás','Vila Nova do Ceira'],
    'Lousã': ['Figueiró do Campo e Casal de Ermio','Lousã','Serpins','Vilarinho'],
    'Mira': ['Carapelhos e Portomar','Mira','Praia de Mira','Seixo'],
    'Miranda do Corvo': ['Lamas','Miranda do Corvo','Rio de Vide','Semide e Vila Nova do Ceira','Vendas de Galizes e Alvares'],
    'Montemor-o-Velho': ['Abrunheira, Vernada e Converting','Carapinheira','Ereira','Liceia','Meã e Carapinheira','Montemor-o-Velho e Gatões','Pereira','Santo Varão','Seixo de Gatões','Tentúgal'],
    'Oliveira do Hospital': ['Alvares','Avô','Bobadela','Ervedal e Vila Franca da Beira','Lagares da Beira','Lagos da Beira e Lajeosa','Lourosa','Meruge','Nogueira do Cravo','Oliveira do Hospital','Penalva de Alva','Santa Ovaia','São Gião','São Sebastião da Feira','Travanca de Lagos'],
    'Pampilhosa da Serra': ['Dornelas do Zêzere','Janeiro de Cima','Pessegueiro','Pampilhosa da Serra','Portela do Fôjo','Unhais-o-Velho','Vila Cova do Alva'],
    'Penacova': ['Carvalho','Friúmes e Paradela','Lorvão','Oliveira do Mondego e Travanca do Mondego','Penacova','São Paio de Mondego','Sazes do Lorvão','Tentúgal (ver)'],
    'Penela': ['Cumeeira','Espinhal','Penela (Santa Eufémia) e Penela (São Miguel)','São Miguel','Vila Nova de Anços e Bolho'],
    'Soure': ['Alfarelos e Jorge','Brunhós','Degracias','Figueiró do Campo','Pombalinho','Samuel','Soure','Vinha da Rainha'],
    'Tábua': ['Candosa','Carroco','Covas e Vila Nova de Oliveirinha','Espariz','Mouronho','Póvoa de Midões','Pinheiro de Coja','São João da Boa Vista','Tábua'],
    'Vila Nova de Poiares': ['Arrifana','São Miguel de Poiares','Vila Nova de Poiares'],
  },
  'Évora': {
    'Alandroal': ['Alandroal (Nossa Senhora da Conceição), São Brás dos Matos (Mina do Bugalho) e Juromenha (Nossa Senhora do Loreto)','Capelins (Santo António)','Terena (São Pedro)'],
    'Arraiolos': ['Arraiolos','Igrejinha','Santa Justa','São Gregório e São Sebastião da Giesteira','Vimieiro'],
    'Borba': ['Borba (Matriz)','Borba (São Bartolomeu)','Rio de Moinhos','Orada'],
    'Estremoz': ['Arcos','Estremoz (Santa Maria e Santo André)','Glória','Ijuízes','Santa Vitória do Ameixial','São Bento de Ana Loura e Cabeça de Carneiro','São Bento do Cortiço e Santo Estêvão','São Domingos de Ana Loura','Veiros'],
    'Évora': ['Bacelo e Senhora da Saúde','Canaviais','Évora (São Mamede, Sé, São Pedro e Santo Antão)','Horta das Figueiras','Malagueira e Horta das Figueiras','Nossa Senhora de Machede','São Manços e São Vicente do Pigeiro','São Miguel de Machede','Torre de Coelheiros'],
    'Montemor-o-Novo': ['Cabrela','Ciborro','Cortiçadas de Lavre e Lavre','Foros de Vale de Figueira','Montemor-o-Novo','Nossa Senhora da Vila, Nossa Senhora do Bispo e Silveiras','Santiago do Escoural'],
    'Mora': ['Cabeção','Mora','Pavia','Torre de Coelheiros (ver Évora)'],
    'Mourão': ['Granja','Luz','Mourão'],
    'Portel': ['Amieira','Monte do Trigo','Oriola','Portel','Santana','São Bartolomeu do Outeiro','Vera Cruz'],
    'Redondo': ['Montoito','Redondo'],
    'Reguengos de Monsaraz': ['Campo','Corval','Monsaraz','Reguengos de Monsaraz'],
    'Vendas Novas': ['Landeira','Vendas Novas'],
    'Viana do Alentejo': ['Aguiar','Alcáçovas','Viana do Alentejo'],
    'Vila Viçosa': ['Bencatel','Ciladas','Pardais','Vila Viçosa'],
  },
  'Faro': {
    'Albufeira': ['Albufeira e Olhos de Água','Ferreiras','Guia','Paderne'],
    'Alcoutim': ['Alcoutim e Pereiro','Giões','Martim Longo','Vaqueiros'],
    'Aljezur': ['Aljezur','Bordeira','Odeceixe','Rogil'],
    'Castro Marim': ['Altura','Castro Marim','Odeleite'],
    'Faro': ['Conceição e Estoi','Faro (Montenegro e Manuel Bivar)','Faro (Sé e São Pedro)','Santa Bárbara de Nexe'],
    'Lagoa': ['Estômbar e Parchal','Ferragudo','Lagoa e Carvoeiro','Porches'],
    'Lagos': ['Bensafrim e Barão de São João','Lagos (São Sebastião e Santa Maria)','Luz','Odiáxere'],
    'Loulé': ['Almancil','Alte','Ameixial','Boliqueime','Loulé (São Clemente)','Loulé (São Sebastião)','Quarteira','Querença, Tôr e Benafim','Salir'],
    'Monchique': ['Marmelete','Monchique','Alferce'],
    'Olhão': ['Fuseta','Moncarapacho e Fuseta','Olhão','Pechão','Quelfes'],
    'Portimão': ['Alvor','Mexilhoeira Grande','Portimão'],
    'São Brás de Alportel': ['São Brás de Alportel'],
    'Silves': ['Alcantarilha e Pêra','Algoz e Tunes','Armação de Pêra','Silves','São Bartolomeu de Messines','São Marcos da Serra'],
    'Tavira': ['Cachopo','Conceição e Cabanas de Tavira','Santa Catarina da Fonte do Bispo','Santo Estêvão','Tavira (Santa Maria e Santiago)','Luz de Tavira e Santo Estêvão'],
    'Vila do Bispo': ['Budens','Raposeira','Sagres','Vila do Bispo e Raposeira'],
    'Vila Real de Santo António': ['Monte Gordo','Vila Nova de Cacela','Vila Real de Santo António'],
  },
  'Guarda': {
    'Aguiar da Beira': ['Aguiar da Beira e Coruche','Carapito','Dornelas','Eirado','Forninhos','Pinheiro','Sequeiros e Gradiz','Valverde'],
    'Almeida': ['Almeida','Amoreira','Azinhal','Cabreira','Castelo Bom','Castelo Mendo','Freineda','Freixo','Junça e Ade','Leomil, Mido, Moita e Penalobo','Malhada Sorda','Mesquitela e Azinhal','Miuzela','Monte Perobolso','Parada','Peva','Porto de Ovelha','Senouras','Vale da Mula','Valverde','Vilar Formoso','Vilar Maior'],
    'Celorico da Beira': ['Açores','Aguiar da Beira (ver)','Carvalhal','Casas do Soeiro','Celorico (São Pedro e São João)','Cortiçô da Serra','Faia','Fornos de Algodres (ver)','Lageosa do Mondego','Lajeosa do Mondego','Mezio','Minhocal','Ratoeira','Rapa','Rio Torto','Salgueirais','Santa Eufémia','Valhelhas'],
    'Figueira de Castelo Rodrigo': ['Almofala','Algodres e Freixedas (ver Fornos de Algodres)','Castelo Rodrigo','Cidadelhe','Escalhão','Freixeda do Torrão','Mata de Lobos','Penha de Águia','Quinta do Côvo','Reigada','Vale de Afonsinho','Vilar de Amargo'],
    'Fornos de Algodres': ['Algodres','Carapito (ver Aguiar da Beira)','Figueiró da Granja','Fornos de Algodres','Fuinhas','Lajeosa','Maceira','Matança','Muxagata','Quintas de São Bartolomeu','Sobral Pichorro','Vila Chã'],
    'Gouveia': ['Arcozelo','Cativelos','Figueiró da Serra e Freixo da Serra','Gouveia (São Julião e São Pedro)','Lagarinhos','Melo','Nabais','Nespereira','Paços da Serra','Rio Torto (ver Celorico)','Riodades','Sabugueiro','São Paio','Torroselo','Vinhó'],
    'Guarda': ['Aldeia Viçosa','Alvendre','Arrifana','Avelãs da Ribeira e Avelãs de Ambom','Casal de Cinza','Castanheira','Corujeira','Famalicão','Fernão Joanes','Gonçalo','Gonçalo Bocas','João Antão','Jarmelo São Miguel e Jarmelo São Pedro','Maçainhas','Marcolino','Monte Margarida','Panoias de Cima','Pega','Porto da Carne','Ramela','Rochoso','São Miguel da Guarda','Sé','Sobral da Serra','Trinta','Valhelhas (ver Celorico)','Vela','Videmonte','Vila Fernando','Vila Franca do Deão','Vila Soeiro','Vilar Torpim'],
    'Manteigas': ['Manteigas (Santa Maria)','Manteigas (São Pedro)','Vale de Amoreira'],
    'Mêda': ['Aveloso','Barreira','Casteição','Coriscada','Longroiva','Marialva','Mêda','Meimoa','Outeiro de Gatos','Pai Penela','Poço do Canto','Prova','Rabaçal','Vale Flor'],
    'Pinhel': ['Atalaia','Azevo','Bogalhal','Ervedosa','Freixedas','Lamegal','Lameiras','Pala','Pinhel','Póvoa d\'El Rei','Ranhados','Safurde','Santa Eufémia','Souro Pires','Vascoveiro','Vermosa','Vila Maior','Vila Verde'],
    'Sabugal': ['Aldeia da Ponte','Aldeia do Bispo (ver Penamacor)','Aldeia Velha','Alfaiates','Baraçal','Bendada','Bismula','Caria (ver Belmonte)','Casteleiro','Forcalhos','Lajeosa','Lageosa','Moita','Nave','Pena Lobo','Penalobo','Quadrazais','Quintas de São Bartolomeu','Rapoula do Côa','Rebolosa','Rendo','Ruivós','Sabugal','Sortelha','Seixo do Côa','Soito','Vale das Éguas','Vilar Maior (ver Almeida)','Vilar do Monte'],
    'Seia': ['Aldeia das Dez','Alvoco da Serra','Cabeça','Carragosela','Casa Nova','Destriz','Folhadosa','Girabolhos','Loriga','Lousã (ver Coimbra)','Paranhos','Pinhanços','Sabugueiro (ver Gouveia)','Santa Comba','Santa Eulália','Santiago','São Martinho','São Romão','Seia','Tourais','Travancinha','Valezim','Vide','Vila Cova à Coelheira'],
    'Trancoso': ['Aldeia Nova','Almofala (ver Figueira de C.R.)','Beatriz','Carnicães','Caria','Feital','Fiães','Granja','Guilheiro','Lajeosa do Mondego','Marialva (ver Mêda)','Moimentinha','Moreira de Rei','Póvoa do Concelho','Rio de Mel','São Marcos','Tamanhos','Terrenho','Torre do Terrenho','Trancoso (Santa Maria e São Pedro e São Marcos)','Valdanta','Vale do Seixo','Vila Franca das Naves','Vila Garcia','Vilares','Vilaseca'],
    'Vila Nova de Foz Côa': ['Almendra','Castelo Melhor','Cedovim','Chãs de Égua','Custóias','Freixo de Numão','Horta','Muxagata (ver Fornos de Algodres)','Mós','Numão','Olho Marinho','Paradela','Riodades (ver Gouveia)','Sandão','São Marcos','Touça','Vale de Figueira','Vila Nova de Foz Côa','Vila Verde'],
  },
  'Leiria': {
    'Alcobaça': ['Alcobaça e Vestiaria','Alfeizerão','Aljubarrota (Prazeres e São Lourenço)','Alpedriz','Bárrio e Pataias','Benedita','Cela','Coz, Alpedriz e Montes','Évora de Alcobaça','Maiorga','Turquel','Vimeiro'],
    'Alvaiázere': ['Alvaiázere','Almoster','Maçãs de Caminho e Maçãs de D. Maria','Pelmá','Pussos São Pedro e São João'],
    'Ansião': ['Ansião','Avelar','Chão de Couce','Lagares','Pousaflores','Torre de Vilela'],
    'Batalha': ['Batalha','Golpilheira','Reguengo do Fetal','São Mamede'],
    'Bombarral': ['Bombarral','Carvalhal','Orders','Roliça'],
    'Caldas da Rainha': ['A-dos-Francos','Alvorninha','Carvalhal Benfeito e Covão do Lobo','Caldas da Rainha - Nossa Senhora do Pópulo, Coto e São Gregório','Caldas da Rainha - Santo Onofre e Serra do Bouro','Foz do Arelho','Nadadouro','Salir de Matos e Santa Catarina','Santa Catarina','Tornada e Salir do Porto','Vidais'],
    'Castanheira de Pêra': ['Castanheira de Pêra e Coentral'],
    'Figueiró dos Vinhos': ['Arega','Figueiró dos Vinhos e Bairradas'],
    'Leiria': ['Amor','Arrabal','Bajouca','Bidoeira de Cima','Caranguejeira e Santa Catarina da Serra','Colmeias e Memória','Leiria','Leiria, Pousos, Barreira e Cortes','Maceira','Marrazes e Barosa','Milagres','Monte Real e Carvide','Ortigosa','Porto de Mós (ver)','Regueira de Pontes','Santa Eufémia','Souto da Carpalhosa e Ortigosa'],
    'Marinha Grande': ['Fonte Boa do Mondego','Marinha Grande','Moita','São Pedro de Muel'],
    'Nazaré': ['Famalicão','Nazaré','Valado dos Frades'],
    'Óbidos': ['A-dos-Negros','Amoreira','Gaeiras','Olho Marinho','Óbidos e Usseira','Reicha e Tojeira','Santa Maria, São Pedro e Sobral da Lagoa','Vau'],
    'Pedrógão Grande': ['Graça e Pedrógão Grande','Pedrógão Pequeno (ver Sertã)'],
    'Peniche': ['Atouguia da Baleia','Ferrel','Peniche'],
    'Pombal': ['Abiul','Albergaria dos Doze e Machio','Almagreira','Antanhol (ver Coimbra)','Carnide','Carriço','Guia','Ilha','Meirinhas','Pelariga','Pombal','Rama','Santiago e São Simão de Litém e Albergaria dos Doze','Redinha','Santiago da Guarda','São Simão de Litém'],
    'Porto de Mós': ['Alqueidão da Serra','Alvados e Alcaria','Juncal','Mira de Aire','Porto de Mós - São João Baptista e São Pedro','Serra de Santo António','Serro Ventoso','Valverde e Serra de Santo António'],
  },
  'Lisboa': {
    'Alenquer': ['Abrigada e Cabanas de Torres','Alenquer (Santo Estêvão e Triana)','Aldeia Galega da Merceana e Aldeia Gavinha','Cadafal e Moçafaneira','Cabanas de Torres','Carregado e Rio Grande','Meca','Olhalvo','Ota','Ribaldeira','Ventosa','Vila Verde dos Francos'],
    'Amadora': ['Alfragide','Brandoa','Buraca','Damaia','Falagueira-Venda Nova','Mina de Água','Reboleira','Venteira'],
    'Arruda dos Vinhos': ['Arruda dos Vinhos','Cardosas e Santiago dos Velhos','Arranhó'],
    'Azambuja': ['Alcoentre','Azambuja','Aveiras de Baixo','Aveiras de Cima','Maçussa','Vale do Paraíso','Vila Nova da Rainha'],
    'Cadaval': ['Alguber','Cadaval e Pêro Moniz','Cercal','Lamas e Cercal','Painho e Figueiros','Vermelha'],
    'Cascais': ['Alcabideche','Cascais e Estoril','Parede','São Domingos de Rana'],
    'Lisboa': ['Ajuda','Alcântara','Alvalade','Areeiro','Arroios','Avenidas Novas','Beato','Belém','Benfica','Campo de Ourique','Campolide','Carnide','Estrela','Lumiar','Marvila','Misericórdia','Olivais','Parque das Nações','Penha de França','Santa Clara','Santa Maria Maior','Santo António','São Domingos de Benfica','São Vicente'],
    'Loures': ['Bucelas','Camarate, Unhos e Apelação','Fanhões','Frielas','Loures','Lousa','Moscavide e Portela','Odivelas (ver)','Prior Velho','Santo Antão e São Julião do Tojal','Santo António dos Cavaleiros e Frielas','São João da Talha'],
    'Lourinhã': ['Lourinhã e Atalaia','A-dos-Cunhados e Maceira','Moledo','Ribamar','Santa Bárbara','São Bartolomeu dos Galegos e Moledo','Vimeiro'],
    'Mafra': ['Azueira e Sobral da Abelheira','Carvoeira','Cheleiros','Encarnação','Enxara do Bispo, Gradil e Vila Franca do Rosário','Ericeira','Igreja Nova e Cheleiros','Mafra','Malveira e Serra de El-Rei','Milharado','Santo Isidoro','Venda do Pinheiro e Santo Estêvão das Galés','Vila do Milharado'],
    'Odivelas': ['Caneças','Famões','Odivelas','Olival Basto e Pontinha','Pontinha e Famões','Póvoa de Santo Adrião e Olival Basto'],
    'Oeiras': ['Algés, Linda-a-Velha e Cruz Quebrada-Dafundo','Barcarena','Carnaxide e Queijas','Oeiras e São Julião da Barra, Paço de Arcos e Caxias'],
    'Sintra': ['Agualva e Mira-Sintra','Almargem do Bispo, Pêro Pinheiro e Montelavar','Belas','Casal de Cambra','Colares','Massamá e Monte Abraão','Mem Martins','Queluz e Belas','Rio de Mouro','Santa Maria e São Miguel, São Martinho e São Pedro de Penaferrim','São João das Lampas e Terrugem'],
    'Sobral de Monte Agraço': ['Compromisso','Santo Quintino','Sobral de Monte Agraço'],
    'Torres Vedras': ['A-dos-Cunhados e Maceira','Campelos e Outeiro da Cabeça','Carmões e Turcifal','Carvoeira (ver Mafra)','Dois Portos e Runa','Freiria','Maxial e Monte Redondo','Ramalhal','Ribaldeira (ver Alenquer)','Santa Maria, São Pedro e Matacães','São Pedro da Cadeira','Torres Vedras'],
    'Vila Franca de Xira': ['Alverca do Ribatejo e Sobralinho','Arcena e Castanheira do Ribatejo','Alhandra, São João dos Montes e Calhandriz','Forte da Casa','Póvoa de Santa Iria e Forte da Casa','Vialonga','Vila Franca de Xira'],
  },
  'Portalegre': {
    'Alter do Chão': ['Alter do Chão','Chancelaria','Cunheira','Seda'],
    'Arronches': ['Arronches','Assunção','Esperança'],
    'Avis': ['Aldeia Velha','Avis','Benavila e Valongo','Ervedal e Vale de Maceira','Maranhão','Valongo'],
    'Campo Maior': ['Campo Maior','Nossa Senhora da Expectação','São João Baptista'],
    'Castelo de Vide': ['Castelo de Vide','Santa Maria de Marvão (ver Marvão)'],
    'Crato': ['Aldeia da Mata','Belver','Crato e Mártires','Flor da Rosa','Monte da Pedra','Vale do Peso'],
    'Elvas': ['Assunção, Ajuda, Salvador e Santo Ildefonso','Barbacena','Caia, São Pedro e São Brás','Santa Eulália','Terrugem e Vila Boim','Varche'],
    'Fronteira': ['Cabeço de Vide','Fronteira','São Saturnino'],
    'Gavião': ['Belver (ver Crato)','Comenda','Gavião','Margem'],
    'Marvão': ['Beirã','Marvão','São Salvador de Aramenha','Santo António das Areias'],
    'Monforte': ['Assumar','Monforte','Sabugueiro e Santo Aleixo'],
    'Nisa': ['Alpalhão','Arez e Amieira do Tejo','Espírito Santo e São Matias','Montalvão','Nisa','Santana','Tolosa'],
    'Ponte de Sor': ['Foros de Arrão','Galveias','Longomel','Montargil','Ponte de Sor, Tramaga e Vale de Açor'],
    'Portalegre': ['Alagoa','Alegrete','Fortios','Portalegre','Reguengo e São Julião','Ribeira de Nisa e Carreiras','São Julião','Sé e São Lourenço','Urra'],
    'Sousel': ['Casa Branca','Cano','Santo Amaro','Sousel'],
  },
  'Porto': {
    'Amarante': ['Aboadela, Sanche e Várzea','Ansiães','Bustelo, Carneiro e Carvalho de Rei','Canadelo e Oliveira','Figueiró (Santiago e Santa Cristina)','Fridão','Gatão','Jazente','Louredo','Lufrei','Mancelos','Marão','Mondim de Basto (ver Vila Real)','Oliveira, São Mateus e Pinheiro','Padronelo','Real','Rebordelo e Telões','Salvador do Monte','Sanche','São Gonçalo','Travanca','Valbom'],
    'Baião': ['Ancede e Ribadouro','Campelo','Frende','Gestaçô','Gove','Grilo','Loivos da Ribeira e Mondim da Beira','Loivos do Monte e Baião','Santa Cruz do Douro','São João de Medelo','Teixeira','Tresouras','Viariz'],
    'Felgueiras': ['Airães','Borba de Godim','Caramos','Castelãos','Friande','Idães','Jugueiros','Lagares','Macieira da Lixa e Caramos','Margaride (Santa Eulália), Várzea, Lagares, Varziela e Moure','Moure e Ribeirão','Pinheiro','Regilde e Torrados','Revinhade','Riba de Vizela (São Pedro e Santa Cristina)','Sendim','Torrados','Várzea'],
    'Gondomar': ['Baguim do Monte (Rio Tinto)','Fânzeres e São Pedro da Cova','Foz do Sousa e Covelo','Gondomar (São Cosme), Valbom e Jovim','Lomba','Melres e Medas','Rio Tinto'],
    'Lousada': ['Aveleda','Caíde de Rei','Cristelos, Boim e Ordem','Figueiras','Lodares','Lousada','Lustosa e Barrosas (Santo Estêvão)','Marachão','Meinedo','Nevogilde','Nogueira','Silvares','Sousela','Torno','Vilar do Torno e Alentém'],
    'Maia': ['Águas Santas','Avioso (Santa Maria) e Avioso (São Pedro)','Barca','Castêlo da Maia','Folgosa','Gemunde','Gondim e Maia','Milheirós','Moreira','Nogueira e Silva Escura','São Pedro Fins e Barca','Silva Escura','Vermoim'],
    'Marco de Canaveses': ['Alpendorada, Matos e Sobretâmega','Ariz e Maureles','Banho e Carvalhosa','Constance','Constância','Douro e Tâmega','Folhada','Freixo','Magrelos','Manhuncelos','Maureles','Paços de Gaiolo','Paredes de Viadores e Manhuncelos','Penha Longa e Paços de Gaiolo','São Nicolau','Soalhães','Tabuado','Tuias','Vila Boa de Quires e Maureles','Várzea, Aliviada e Folhada'],
    'Matosinhos': ['Custóias, Leça do Balio e Guifões','Lavra, Santa Cruz do Bispo e Mindelo','Matosinhos e Leça da Palmeira','Perafita, Lavra e Santa Cruz do Bispo','São Mamede de Infesta e Senhora da Hora'],
    'Paços de Ferreira': ['Arreigada','Carvalhosa','Eiriz','Ferreira','Figueiró','Frazão e Arreigada','Freamunde','Meixomil','Paços de Ferreira','Penamaior','Raimonda','Sanfins de Ferreira, Areosa e Codessos','Seroa'],
    'Paredes': ['Baltar','Beire','Besteiros','Bitarães','Cristelo','Duas Igrejas','Gandra','Lordelo','Louredo','Luzim e Vila Cova de Carros','Mouriz','Parada de Todeia','Paredes','Rebordosa','Recarei','Sobrosa','Vandoma','Vilela e Sobrosa'],
    'Penafiel': ['Abragão','Boelhe','Bustelo','Cabeça Santa','Canelas','Capela','Castelões','Croca','Eja','Fonte Arcada e Ribeirão','Galegos','Guilhufe e Urrô','Irivo','Lagares e Figueira','Luzein','Marecos','Milhundos','Paço de Sousa','Perozelo','Portela e Covelo','Rans','Rio de Moinhos','Sebolido','São Martinho de Recezinhos','Termas de São Vicente e Recezinhos','Vila Cova da Lixa e Borba de Godim'],
    'Porto': ['Aldoar, Foz do Douro e Nevogilde','Bonfim','Campanhã','Cedofeita, Ildefonso, Sé, Miragaia, Nicolau e Vitória','Lordelo do Ouro e Massarelos','Paranhos','Ramalde'],
    'Póvoa de Varzim': ['Aguçadoura e Navais','Amorim','Balazar','Beiriz e Argivai','Estela','Laundos','Milheirós de Poiares (ver Santa Maria da Feira)','Póvoa de Varzim','Rates','Terroso'],
    'Santo Tirso': ['Agrela e Caldas de Vizela (ver Vizela)','Água Longa','Areias e Pias','Burgães','Carreira e Refojos de Riba de Ave','Couto (Santa Cristina e São Miguel)','Covelas','Guimarei','Lamelas','Lousado (ver Vila Nova de Famalicão)','Lousado','Medir','Monte Córdova','Negrelos (São Mamede) e Negrelos (São Tomé)','Rebordões','Santo Tirso','São Martinho do Campo e Santiago de Bougado','São Miguel do Couto','São Tomé de Negrelos','Vilarinho'],
    'Trofa': ['Alvarelhos e Guidões','Bougado (São Martinho e Santiago)','Coronado (São Mamede e São Romão)','Muro'],
    'Valongo': ['Alfena e Campo','Ermesinde','Valongo e Sobrado'],
    'Vila do Conde': ['Arcos','Árvore','Aveleda','Azurara e Vairão','Bagunte, Ferreiró, Outeiro Maior e Macieira da Maia','Canidelo','Fajozes','Fornelo e Vairão','Gião','Guilhabreu','Labruge','Macieira da Maia','Mindelo','Modivas','Montenegro (ver Faro)','Modivas','Mosteiró','Nogueira','Parada','Retorta e Tougues','Rio Mau e Arcos','Touguinha e Touguinhó','Touguinho','Vairão','Varziela','Vilar'],
    'Vila Nova de Gaia': ['Arcozelo','Avintes','Canelas e Espinho (ver)','Canidelo','Grijó e Sermonde','Gulpilhares e Valadares','Madalena','Oliveira do Douro','Pedroso e Seixezelo','Sandim, Olival, Lever e Crestuma','Santa Marinha e São Pedro da Afurada','São Félix da Marinha','Serzedo e Perosinho','Vilar de Andorinho','Vilar do Paraíso'],
  },
  'Santarém': {
    'Abrantes': ['Abrantes (Rossio ao Sul do Tejo)','Abrantes (São João, São Vicente e São Sebastião)','Aldeia do Mato e Souto','Alvega e Concavada','Bemposta','Carvalhal','Fontes','Martinchel e Barca','Mouriscas','Pego','Rio de Moinhos','São Facundo e Vale das Mós','Souto'],
    'Alcanena': ['Alcanena e Vila Moreira','Bugalhos','Espinheiro','Minde','Monsanto e Casalinho','Santiago de Montalegre','Serra de Santo António'],
    'Almeirim': ['Almeirim','Benfica do Ribatejo','Fazendas de Almeirim'],
    'Alpiarça': ['Alpiarça'],
    'Benavente': ['Barrosa e Santo Estêvão','Benavente','Samora Correia'],
    'Cartaxo': ['Cartaxo e Vale da Pinta','Ereira e Lapa','Pontével','Vale da Pinta','Vila Chã de Ourique'],
    'Chamusca': ['Chamusca e Pinheiro Grande','Chouto','Parreira e Chouto','Pinheiro Grande','Ulme','Vale de Cavalos'],
    'Constância': ['Constância e Santa Margarida da Coutada'],
    'Coruche': ['Branca','Coruche, Fajarda e Erra','Couço','São José da Lamarosa','Santana do Mato'],
    'Entroncamento': ['Entroncamento'],
    'Ferreira do Zêzere': ['Beco','Chãos','Ferreira do Zêzere','Igreja Nova do Sobral','São Pedro do Esteval (ver Proença)'],
    'Golegã': ['Azinhaga','Golegã'],
    'Mação': ['Aboboreira','Cardigos','Carvoeiro','Envendos','Mação','Ortiga'],
    'Ourém': ['Atouguia e Santiago de Montalegre','Caxarias','Espite e Formigais','Fátima','Freixianda, Ribeira do Fárrio e Formigais','Gondemaria e Olival','Nossa Senhora das Misericórdias','Ourém','Seiça','Urqueira'],
    'Rio Maior': ['A dos Francos (ver Torres Vedras)','Alcobertas','Arrouquelas','Asseiceira','Azambujeira e Malaqueijo','Fráguas','Marmeleira e Rio Maior','Ribeira de São João'],
    'Salvaterra de Magos': ['Foros de Salvaterra','Glória do Ribatejo','Granho','Muge','Salvaterra de Magos'],
    'Santarém': ['Achete, Azoia de Baixo e Póvoa de Santarém','Alcanede','Almoster e Casével','Azoia de Cima e Tremês','Casével e Vaqueiros','Garvão e Santa Luzia','Moçarria','Pernes','Santa Iria da Ribeira de Santarém','Santarém (Marvila)','Santarém (São Salvador) e Santarém (São Nicolau)','São Vicente do Paul e Vale de Figueira'],
    'Sardoal': ['Alcaravela e Santiago de Montalegre','Atalaia','Sardoal','Valhascos'],
    'Tomar': ['Além da Ribeira e Pedreira','Beselga','Casais e Alviobeira','Constância (ver)','Paialvo','Serra e Junceira','Tomar (São João Baptista) e Santa Maria dos Olivais'],
    'Torres Novas': ['Alcorochel e Assentiz','Brogueira, Parceiros de Igreja e Alcorochel','Lapas','Meia Via','Olaia e Paço','Pedrógão','Riachos','Ribeira Branca e Paço','Torres Novas (São Pedro), Lapas e Ribeira Branca','Torres Novas (Santiago) e Torres Novas (São Pedro)','Zibreira'],
    'Vila Nova da Barquinha': ['Atalaia (ver Sardoal)','Moita do Norte','Praia do Ribatejo','Tancos','Vila Nova da Barquinha'],
  },
  'Setúbal': {
    'Alcácer do Sal': ['Alcácer do Sal (Santiago) e Santa Susana','Comporta','Grândola (ver)','Palma e Alcácer do Sal','São Martinho e Santa Margarida do Sado'],
    'Alcochete': ['Alcochete','Samouco','São Francisco'],
    'Almada': ['Almada, Cova da Piedade, Pragal e Cacilhas','Caparica e Trafaria','Costa da Caparica','Laranjeiro e Feijó','Sobreda'],
    'Barreiro': ['Alto do Seixalinho, Santo André e Verderena','Barreiro e Lavradio','Coina','Sts. e Santo António da Charneca'],
    'Grândola': ['Azinheira dos Barros e São Mamede do Sádão','Carvalhal','Grândola','Melides','Santa Margarida da Serra'],
    'Moita': ['Alhos Vedros','Baixa da Banheira e Vale da Amoreira','Moita','Sarilhos Pequenos'],
    'Montijo': ['Afonsoeiro','Atalaia e Alto Estanqueiro-Jardia','Canha e Santo Isidro de Pegões','Gaio-Rosário e Sarilhos Grandes','Montijo','Pegões','Santo Isidro de Pegões'],
    'Palmela': ['Marateca e Poceirão','Palmela','Pinhal Novo','Quinta do Anjo','Setúbal (ver)'],
    'Santiago do Cacém': ['Abela','Alvalade','Cercal do Alentejo','Ermidas-Sado','Ribeira de São João (ver Rio Maior)','Santiago do Cacém','Santo André','São Bartolomeu da Serra','São Domingos','São Francisco da Serra','Sonega'],
    'Seixal': ['Aldeia de Paio Pires','Amora','Corroios','Fernão Ferro','Seixal, Arrentela e Aldeia de Paio Pires'],
    'Sesimbra': ['Castelo','Santiago','Sesimbra (Santiaogo) e Sesimbra (Castelo)'],
    'Setúbal': ['Azeitão (São Lourenço e São Simão)','Gâmbia, Pontes e Alto da Guerra','São Sebastião','Setúbal (São Julião, Nossa Senhora da Anunciada e Santa Maria da Graça)','Setúbal (São Simão)'],
    'Sines': ['Porto Covo','Sines'],
  },
  'Viana do Castelo': {
    'Arcos de Valdevez': ['Arcos de Valdevez (Aguiã, Giela, Rio Frio e Padreiro)','Arcos de Valdevez (Salvador, Silveiros, Gavieira, Jolda Madalena)','Eiras, Prozelo, Alvora e Abedim','Grade e Sabadim','Guilhadeses e Santar','Padreiro (Salvador e Santa Cristina)','Sistelo, Ázere e Cabreiro','Soajo e Lindoso'],
    'Caminha': ['Âncora','Argela e Vila Praia de Âncora','Caminha (Matriz e Vilarelho)','Cristelo e Moledo do Minho','Dem','Gondar e Orbacém','Lanhelas e Riba de Âncora','Moledo e Cristelo','Seixas','Venade'],
    'Melgaço': ['Castro Laboreiro e Lamas de Mouro','Chaviães','Cousso e Prado','Cristoval','Fiães e Santar','Gave','Lamas de Mouro','Melgaço','Paderne','Parada do Monte','Prado e Fiães','Remoães','São Paio'],
    'Monção': ['Abedim','Barbeita e Lara','Barroças e Taias','Bela e Parada','Cambeses','Ceivães e Badim','Cortes','Cristoval','Mazedo e Cortes','Messegães, Valadares e Sá','Monção','Moreira','Parada de Todeia (ver Paredes)','Pias','Podame e Oleiros','Portela','Regalados, Gavião e Sabajães','Sago, Lordelo e Parada','Tangil e Ressegueiros','Troporiz','Trute'],
    'Paredes de Coura': ['Bico','Coura e Óis','Cristoval','Formariz','Insalde e Porreiras','Mozelos e Cunha','Padornelo e Gandra','Paredes de Coura','Resende','Romarigães e Cossourado','Rubiães e Fontoura','Tregosa e Abedim'],
    'Ponte da Barca': ['Bravães','Britelo, Germil e Pões','Crasto, Ruivos e Gomide','Entre Ambos os Rios, Ermida e Germil','Lavradas e Oleiros','Lindoso (ver Arcos de Valdevez)','Ponte da Barca','Touvedo (São Lourenço e Salvador)','Vade (São Pedro), Vade (São Tomé) e Vade (Santa Maria)','Vila Chã (São João Baptista, São Miguel e Santa Maria)'],
    'Ponte de Lima': ['Anais e Cabaços','Beiral do Lima, Moure e Espadanedo','Bertiandos e São Pedro de Arcos','Bravães (ver Ponte da Barca)','Cabração e Moreira do Lima','Calvelo e Gaifar','Calheiros e Vitorino das Donas','Faria, Barnões e Cepões','Fontão e Corona','Fornelos e Queijada','Freixo e Lamelas','Gandra e Azias','Gondufe','Labruja e Labrujó','Navió e Vitorino dos Piães','Poiares e Beiral','Ponte de Lima','Rebordões (Santa Maria) e Rebordões (Souto)','Rendufe','Ribeira e Quartas','São Martinho da Gandra e São Pedro de Arcos (ver Bertiandos)','Seara e São Tomé de Merufe','Serdedelo','Serdedelo e Cunha','Vilar do Monte','Vitorino das Donas e Calheiros'],
    'Valença': ['Boivão e Sanfins','Cerdal','Cristoval (ver Monção)','Fontoura','Gandra','Ganfei e Taião','Igreja','São Pedro da Torre e Verdoejo','São Julião','Sanfins','Valença','Verdoejo'],
    'Viana do Castelo': ['Afife','Alvarães','Amonde, Moreira de Geraz e Deão','Areosa','Barroselas e Carvoeiro','Chafé','Darque','Deão e Amonde','Deocriste e Portuzelo','Freixieiro de Soutelo','Geraz do Lima (Santa Maria, Mentrestido e Moreira)','Lanheses','Mazarefes e Vila Fria','Meadela','Meixedo','Monserrate','Nogueira','Outeiro','Perre','Portela Susã','Santa Marta de Portuzelo','São Romão de Neiva','Serreleis','Torre, Nogueira e Meixedo','Viana do Castelo'],
    'Vila Nova de Cerveira': ['Campos e Vila Meã','Cerveira e Cornes','Covas','Cronos','Gondar e Orbacém (ver Caminha)','Gondar','Loivo e Loivinho','Reboreda','Vila Nova de Cerveira'],
  },
  'Vila Real': {
    'Alijó': ['Alijó, Vilar e Barros','Carlão e Amieiro','Castedo','Favaios','Pegarinhos','Pópulo e Ribalonga','Sanfins do Douro','Santa Eugénia','São Mamede de Ribatua','Vale de Mendiz','Vilar de Maçada','Vilarinho de Cotas'],
    'Boticas': ['Ardãos e Bobadela','Beça','Boticas e Granja','Codessoso, Curros e Fiães do Tâmega','Dornelas','Sapiãos','Vilar'],
    'Chaves': ['Anelhe, Nantes e Soutelo','Arcossó, Selhariz, Roriz e Póvoa de Agrações','Celas e Vilarchão','Cimo de Vila, Calvão e Soutelinho','Ervedeiro e Redondelo','Madalena, Soutelo e Arcossó','Noura e Eiras','Oura','Paradela','Sanfins, Eiras e Sanfins','Santo António de Monforte e Santa Cruz','São Pedro de Agostém e Eiras','Sanjurge e Ribalonga','Seara e Calvão','Selhariz e Arcossó','Soutelinho da Raia e Cimo de Vila','Travancas e Roriz','Vidago, Arcossó, Selhariz e Roriz','Vila Verde da Raia','Vilarandelo e Paradela'],
    'Mesão Frio': ['Barqueiros, Midões e Oliveiros','Mesão Frio (Santo André)','Oliveiros'],
    'Mondim de Basto': ['Atei','Bilhó','Campanhó','Mondim de Basto e Paradança','Vilar de Ferreiros'],
    'Montalegre': ['Cabril','Cervos e Morgade','Chãs','Contim e Fervidelas','Covelães','Donões','Ferral','Fiães do Rio e Mourilhe','Grovelas','Morgade','Mourilhe','Negrões','Outeiro','Padornelo','Padroso','Pitões das Júnias e Paradela','Reigoso','Salto','Santo André','Sarraquinhos','Tourém','Venda Nova','Viade de Baixo e Ferral'],
    'Murça': ['Candedo','Carva e Valongo de Milhais','Fiolhoso','Jou','Murça e Noura','Noura','Palheiros e Murça'],
    'Peso da Régua': ['Godim, Loureiro e Canelas','Lobrigos (São Miguel e Santa Eulália)','Moure e Fontelas','Peso da Régua e Godim','Poiares','Sedielos','Vilarinho dos Freires'],
    'Ribeira de Pena': ['Alvadia','Cerva e Limões','Canedo de Basto (ver Braga)','Santa Marinha, Campo e Ventosa','Santo Aleixo de Além-Tâmega'],
    'Sabrosa': ['Gouvinhas e Paços','Parada de Pinhão','Provesende','Sabrosa','São Cristóvão do Douro','Souto Maior e Vilarinho de São Romão','Torre do Pinhão','Vale de Mendiz (ver Alijó)'],
    'Santa Marta de Penaguião': ['Cumieira','Fontes','Louredo','Medrões','Santa Marta de Penaguião','São João de Lobrigos'],
    'Valpaços': ['Água Revés e Crasto','Algeriz e Novelas','Argeriz','Aveleiras e Veiga de Lila','Bornes de Aguiar','Canaveses','Carrazedo de Montenegro e Fonte de Arcossó','Compostela e São Pedro de Veiga de Lila','Curros e Ervões','Friões','Lebução','Padrela e Tazém','Rio Torto','Sapiãos (ver Boticas)','São Pedro de Veiga de Lila','Valpaços e Sanfins'],
    'Vila Pouca de Aguiar': ['Almargem do Bispo (ver Sintra)','Alvão, Bragadas e Tresminas','Bornes de Aguiar','Capeludos','Cervos','Gouvães do Douro','Lixa do Álvão','Parada de Monteiros','Pensalvos','Sabroso de Aguiar','São Martinho de Anta e Sonim','Telões','Vila Pouca de Aguiar'],
    'Vila Real': ['Abaças','Adoufe e Vilarinho de Samardã','Arroios','Constantim e Vale de Nogueiras','Folhadela','Guiães','Lordelo','Mouçós e Lamares','Nogueira e Vila Cova','Parada de Cunhos','São Tomé do Castelo e Justes','Torgueda','Vilarinho de Samardã','Vila Real'],
  },
  'Viseu': {
    'Armamar': ['Armamar','Fontelo e Queimada','Goujoim','Queimada','Queimadela','Santo Adrião','São Cosmado','São Martinho das Chãs','Vacalar'],
    'Carregal do Sal': ['Beijós e Carvalhal','Carregal do Sal','Currelos, Sobral e Moura','Santa Luzia','Oliveira do Conde'],
    'Castro Daire': ['Almofei','Alva','Baltar','Castro Daire','Cujó e Lage','Gosende, Zonho e Parade','Mamouros e Alva','Mezio e Moura','Monteiras e Figueiredo','Parada de Ester','Pepim e Mões','Picão','Reriz e Gafanhão'],
    'Cinfães': ['Alhões, Merely, Tendais e Boassas','Bustelo','Cinfães','Fornelos e Canadelo','Gralheira','Moimenta (ver Moimenta da Beira)','Santiago de Piães','São Cristóvão de Nogueira','Tarouquela','Travanca','Vidago (ver Chaves)','Vil do Mato'],
    'Lamego': ['Alvarenga','Britiande','Cambres','Ferreiros de Avões','Figueira','Lalim','Lamego (Almacave e Sé)','Lamego (Nossa Senhora do Bairro)','Lazarim','Parada do Bispo','Penajóia','Samodães','Sande','São João de Fontoura','Valdigem'],
    'Mangualde': ['Abrunhosa-a-Velha','Alcafache e Santiago de Cassurrães','Cunha Alta','Cunha Baixa','Espinho e Senhorim','Fornos de Maceira Dão e Póvoa de Cervães','Lobelhe do Mato e Fornos de Maceira Dão','Mangualde, Mesquitela e Cunha Alta','Mesquitela e Cunha Alta','Orgens','Quintela de Azurara','São João da Fresta e Várzea de Tavares','Unhais da Serra (ver Covilhã)','Várzea de Tavares e São João da Fresta'],
    'Moimenta da Beira': ['Aldeia de Nacomba e Leomil','Ariz','Baldos','Cabaços e Fiães','Caria e Agueira','Caria','Moimenta da Beira','Peva e Vilar','Segões','Sever','Vilar','Vilar de Robra'],
    'Mortágua': ['Almaça','Espinho','Marmeleira e Vale de Remígio','Mortágua, Vale de Remígio, Almaça e Trezói','Pala','Sobral e Monte de Fralães','Trezói'],
    'Nelas': ['Aguieira e Sobral','Canas de Senhorim','Carvalhal Redondo e Aguieira','Lapa do Lobo','Nelas','Senhorim e Canas de Senhorim','Vilar Seco'],
    'Oliveira de Frades': ['Arca e Varzielas','Destriz (ver Rio Maior)','Destriz','Égueira e Vila Chã','Figueiredo das Donas','Oliveira de Frades','Pinheiro','São João da Serra','São Vicente de Lafões'],
    'Penalva do Castelo': ['Antas e Ourozinho','Castelo de Penalva','Ester','Ínsua','Luceu','Lusinde','Meios','Paranhos','Penalva do Castelo','Trancozelos','Vilela'],
    'Penedono': ['Antas e Ourozinho (ver Penalva)','Castelo de Penedono','Penedono e Granja','Póvoa de Penela','Souto'],
    'Resende': ['Anreade e São Romão de Aregos','Cárquere','Felgueiras','Freigil e Miomães','Mouçós (ver Vila Real)','Ovadas','Paus','Resende','São Cipriano e Ovadas'],
    'Santa Comba Dão': ['Couto do Mosteiro e São João do Monte','Nagozelo do Mondego','Santa Comba Dão e Couto do Mosteiro','São João do Monte','Treixedo','Vimieiro'],
    'São João da Pesqueira': ['Castanheiro do Sul','Ervedosa do Douro','Nagozelo do Douro','Riodades (ver Gouveia)','São João da Pesqueira e Várzea de Trevões','Soutelo do Douro','Trevões','Valongo dos Azeites e Paredes da Beira','Vilarouco'],
    'São Pedro do Sul': ['Carvalhais e Candal','Covas do Rio','Fonte de Angeão (ver Vagos)','Figueiredo de Alva','Manhouce','Pinho','Rio de Moinhos','São Félix','São Martinho das Moitas','São Pedro do Sul, Várzea e Baiões','Serrazes','Sul','Várzea'],
    'Sátão': ['Águas Boas','Avelal','Bordonhos','Decermilo','Ferreira de Aves','Mioma','São Miguel de Vila Boa','Sátão','Silvã de Cima','Vila Longa'],
    'Sernancelhe': ['Aldeia de Nacomba (ver Moimenta)','Carvalhal de Vermilhas','Chosendo e Sarzeda','Cunha Baixa (ver Mangualde)','Escurquela e Arnas','Ferreirim','Fonte Arcada e Queimadela (ver Armamar)','Granja de Tedo e Fiães do Rio','Quintela','Sernancelhe','Vila da Ponte','Vila Soeiro do Chão'],
    'Tabuaço': ['Adorigo','Arcos','Desejosa','Granja do Tedo e Fiães do Rio','Lazarim (ver Lamego)','Pinheiros','São Cosmado (ver Armamar)','Sendim','Tabuaço','Távora','Torre de Moncorvo (ver)'],
    'Tarouca': ['Dalvares','Gouviães','Mondim da Beira','Salzedas','São João de Tarouca e Dálvares','Tarouca e Dálvares','Vila Chã da Beira'],
    'Tondela': ['Barreiro de Besteiros e Tourigo','Canas de Santa Maria','Caparrosa','Castelões e Tonda','Dardavaz e São João do Monte','Destriz (ver Santa Comba Dão)','Guardão','Lajeosa e Silvares','Lobão da Beira','Molelos','Parada de Gonta','Santiago de Besteiros e Monte','São Miguel do Outeiro e Sabugosa','São Pedro de França','Tondela','Tonda'],
    'Vila Nova de Paiva': ['Alhais','Cerdeira e Povolide','Leomil','Vila Nova de Paiva'],
    'Viseu': ['Abraveses','Barreiros e Cepões (ver Lamego)','Barreiro de Besteiros (ver Tondela)','Bodiosa','Campo','Coimbrões e Fazendas de Almeirim','Couto de Baixo e Couto de Cima','Fail','Farminhão e Torredeita','Fragosela','Lordosa','Mundão','Orgens','Povolide','Repeses e São Salvador','Rio de Loba','São Cipriano','São João de Lourosa','São Pedro de France','Silgueiros','Torredeita e Farminhão','Várzea de Calde','Vilar de Figueiredo','Viseu'],
    'Vouzela': ['Alcofra','Cambra (ver Vale de Cambra)','Carvalhal das Taípes e Ventosa','Fornelo do Monte','Paços de Vilharigues','Queirã','São Miguel do Mato','Serrazes (ver São Pedro do Sul)','Ventosa','Vouzela','Zlinheira'],
  },
  'Açores': {
    'Angra do Heroísmo': ['Altares','Angra do Heroísmo','Cinco Ribeiras','Doze Ribeiras','Feteira','Porto Judeu','Posto Santo','Raminho','Ribeirinha','Santa Bárbara','São Bartolomeu de Regatos','São Bento','São Mateus da Calheta','São Sebastião','Sé','Terra Chã','Vila de São Sebastião'],
    'Calheta': ['Calheta','Fajã Grande','Fajãzinha','Fazenda','Lajedo','Norte Grande (Graciosa)','Norte Pequeno','Ponta da Ilha','Santa Cruz','Santo Amaro'],
    'Corvo': ['Corvo'],
    'Horta': ['Angústias','Castelo Branco','Cedros','Feteira Grande','Flamengos','Horta','Pedro Miguel','Praia do Almoxarife','Ribeirinha','Salão'],
    'Lagoa': ['Água de Pau','Cabouco','Nossa Senhora do Rosário','Ribeira Chã'],
    'Lajes das Flores': ['Lajes das Flores','Lomba','Ponta dos Ilhéus','Santa Cruz das Flores (ver)'],
    'Lajes do Pico': ['Criação Velha','Lajes do Pico','Piedade','Ribeiras','São Caetano'],
    'Madalena': ['Bandeiras','Candelária','Criação Velha','Madalena','Santo Amaro','São Mateus','Terra do Pão'],
    'Nordeste': ['Achadinha','Nordeste','Nordestinho','Salga','Santana','Santo António de Nordestinho'],
    'Ponta Delgada': ['Arrifes','Candelária','Capelas','Covoada','Fajã de Baixo','Fajã de Cima','Fenais da Luz','Feteiras','Ginetes','La Glória','Livramento','Mosteiros','Pico da Pedra','Pilar','Poço dos Frades','Ponta Delgada','Relva','Remédios','Rosto do Cão (Livramento)','Santa Bárbara','Santa Clara','São José','São Pedro','São Roque','São Sebastião','São Vicente Ferreira','Sete Cidades'],
    'Povoação': ['Água Retorta','Faial da Terra','Furnas','Nossa Senhora dos Remédios','Povoação','Ribeira Quente'],
    'Praia da Vitória': ['Agualva','Biscoitos','Doze Ribeiras (ver Angra)','Fonte do Bastardo','Fontinhas','Guadalupe','Guilherme Moniz','Lajes','Porto Martins','Praia da Vitória','São Brás','Terra Chã (ver Angra)','Vila Nova'],
    'Ribeira Grande': ['Calhetas','Fenais da Ajuda','Lomba da Maia','Maia','Pico Vermelho','Porto Formoso','Rabo de Peixe','Ribeira Grande','Ribeira Seca','Santa Bárbara','São Brás','Vila','Conceição'],
    'Santa Cruz da Graciosa': ['Guadalupe','Luz','Praia','Santa Cruz da Graciosa'],
    'Santa Cruz das Flores': ['Caveira','Cedros (ver Horta)','Fajã Grande (ver Calheta)','Ponta Delgada','Santa Cruz das Flores'],
    'São Roque do Pico': ['Prainha','Santo Amaro (ver Madalena)','São Roque do Pico','Silveira'],
    'Velas': ['Manadas','Norte Grande','Norte Pequeno','Rosais','Santo Amaro','Urzelina','Velas'],
    'Vila do Porto': ['Alvo','Nossa Senhora do Socorro','Santo Espírito','São Pedro','Vila do Porto'],
    'Vila Franca do Campo': ['Água d\'Alto','Ponta Garça','Ribeira das Tainhas','São Miguel','São Pedro','Vila Franca do Campo'],
  },
  'Madeira': {
    'Calheta': ['Arco da Calheta','Calheta','Estreito da Calheta','Fajã da Ovelha','Jardim do Mar','Paul do Mar','Ponta do Pargo','Prazeres'],
    'Câmara de Lobos': ['Câmara de Lobos','Curral das Freiras','Estreito de Câmara de Lobos','Jardim da Serra','Quinta Grande'],
    'Funchal': ['Imaculado Coração de Maria','Monte','Santa Luzia','Santa Maria Maior','Santo António','São Gonçalo','São Martinho','São Pedro','São Roque','Sé'],
    'Machico': ['Água de Pena','Caniçal','Machico','Porto da Cruz','Santo António da Serra'],
    'Ponta do Sol': ['Canhas','Madalena do Mar','Ponta do Sol'],
    'Porto Moniz': ['Achadas da Cruz','Lameiros','Porto Moniz','Ribeira da Janela','Seixal'],
    'Porto Santo': ['Porto Santo'],
    'Ribeira Brava': ['Campanário','Ribeira Brava','Serra de Água','Tabua'],
    'Santa Cruz': ['Camacha','Caniço','Gaula','Santa Cruz','Santo da Serra'],
    'Santana': ['Arco de São Jorge','Faial','Ilha','Santana','São Brás de Alportel (ver Faro)','São Jorge','São Roque do Faial'],
    'São Vicente': ['Boaventura','Ponta Delgada','São Vicente'],
  },
}

export function getDistricts(): string[] {
  return Object.keys(PORTUGAL).sort()
}

export function getConcelhos(district: string): string[] {
  if (!district) return []
  return Object.keys(PORTUGAL[district] || {}).sort()
}

export function getFreguesias(district: string, concelho: string): string[] {
  if (!district && !concelho) return []
  if (district && concelho) {
    return (PORTUGAL[district]?.[concelho] || []).sort()
  }
  if (district && !concelho) {
    const all: string[] = []
    for (const c of Object.values(PORTUGAL[district] || {})) all.push(...c)
    return [...new Set(all)].sort()
  }
  return []
}
